a=int(input('Enter number:'))
print('The binary number is:',bin(a))
print('Hexadecimal of the number is:',hex(a))
print('The octal of the number is:',oct(a))
a=str(input('Enter code to evaluate:'))
eval(a)
a=int(input('Enter real part:'))
b=int(input('Enter imaginary part:'))
print('The complex number is: ',complex(a,b))
a=str(input('Enter object for Boolean operation:'))
print('The boolean output is:',bool(eval(a)))
a="Maggie costs {price} rupees."
b=int(input("Enter price:"))
print(a.format(price=b))
a=float(input('Enter number to round off:'))
print('The number after round off is:',round(a))
a=[]
n=int(input("Enter size of list: "))
for i in range(n):
    b=input(f"Enter input #{i + 1}: ")
    a.append(b)
print("The list is:",a)
print('enumerate:',list(enumerate(a)))
print('ascii():',ascii(a))
print('all():',all(a))
print('any():',any(a))
c=int(input('Enter starting index to slice:'))
d=int(input('Enter ending index slice:'))
e=int(input('Enter steps to slice:'))
print('The list after slicing is:',a[slice(c,d,e)])