import statistics as stat
a=input('Enter elements of tuple:')
b=tuple(int(item) for item in a.split())
print('The tuple is:',b)
print('The lenght of the tuple is:',len(b))
print('The sum of the elements in tuple is:',sum(b))
print('The sorted tuple is:',sorted(b))
print('The minimum element in the tuple is:',min(b))
print('The maximum element in the tuple is:',max(b))
print('The mean of the elements in the tuple is:',stat.mean(b))
x=int(input('Enter element to get value:'))
print('The index of the element is:',b.index(x))
x=int(input('Enter element to get repeatation:'))
print('The repeatation of the element is:',b.count(x))
print('The minimu element in the tuple is:',min(b))
c=int(input('Enter starting index to slice:'))
d=int(input('Enter ending index slice:'))
e=int(input('Enter steps to slice:'))
print('The sliced tuple is:',b[slice(c,d,e)])
a=input('Enter elements of another tuple:')
c=tuple(int(item) for item in a.split())
print('Concatinated tuple:',b+c)