a=input('Enter elements of set:')
b=set(int(item) for item in a.split())
print('The set is:',b)
x=input('Enter item in set:')
b.add(x)
print('The new list is:',b)
x=input('Enter item to remove from set:')
b.remove(x)
print('The new list is:',b)
print('The popped list is:',b.pop())
a=input('Enter elements of another set:')
c=set(int(item) for item in a.split())
print('The second set is:',c)
print('Union of these two sets is:',b.union(c))
print('Disjoint of the two sets:',b.isdisjoint(c))
print('Intersection of these two sets is:',b.intersection(c))
print('Symmetric difference of these two sets is:',b.symmetric_difference(c))
print('Difference from first set to second is:',b.difference(c))
print('Difference from second set to first is:',c.difference(b))
a=b.clear()
print('The first set after clearing:',a)
a=c.clear()
print('The second set after clearing:',a)